### PR TITLE
Add support for 52bit records(FT_RWGENERIC)

### PR DESCRIPTION
**Pull request by twakeman-giti**
Some minor changes to file.go to add branch for 52 bit offsets as well as logic in parse reader for new record size

### CODE REVIEW

**Comment by chrispassas** [comment]
Thank you for your time adding support for additional silk record sizes. To help support this could you provide the following.


- Provide 4 sample files of 1,000 rows with the new 52 size format compressions(none,lzo,snappy,zlib)
- Update README.md supported formats table
- Update test to include the new 52 size files

At minimum I really need a sample data file since I don't have 52 byte files.

It's been a while since I looked at it but rwfilter might have an option to output a certain number of rows.

**Comment by twakeman-giti** [comment]
I can work on that. Thank you for the quick response.

**Comment by chrispassas** [comment]
I reviewed the commit (with test files) but then see you removed them right before I merged.

Don't worry about the test files, I'm going to try to figure out how to convert one of the files I have to your format. I forgot my test files are all the same data so it would be best if the new format test files are the same data as well.

**Comment by chrispassas** [comment]
If you can please send me the rwfileinfo output for your file format.

**Comment by twakeman-giti** [comment]
format(id)          FT_RWGENERIC(0x16)
  version             16
  byte-order          littleEndian
  compression(id)     none(0)
  header-length       104
  record-length       52
  record-version      5
  silk-version        3.19.1
  count-records       1535
  file-size           79924

**Comment by twakeman-giti** [comment]
I created that rw info from running rwptoflow on this capture https://download.netresec.com/pcap/maccdc-2011/maccdc2011_00013_20110312202724.pcap.gz.

**Comment by chrispassas** [comment]
thank you, I added the 52 record to the supported table
https://github.com/chrispassas/silk/blob/master/README.md

**Comment by chrispassas** [comment]
@twakeman-giti I think I found a bug and would like you to help check my fix was correct.

I just created some test files of the new format 52 byte record format using the rwallformats command.
So now in the testdata folder there are test files


- "testdata/FT_RWGENERIC-v5-c0-B.dat",
- "testdata/FT_RWGENERIC-v5-c0-L.dat",
- "testdata/FT_RWGENERIC-v5-c1-B.dat",
- "testdata/FT_RWGENERIC-v5-c1-L.dat",

I think I found a bug in the reading of the 52 byte files. When reading the little endian version of the file the test failed because the src/dst IP were reversed.

I updated the code to reverse the byte order for only the 52 byte files and now the test pass.

Could you pull the latest code v1.3.0 and try on one of your files and let me know if you think the src/dst IP's look correct?

Thank you in advance.

**Comment by twakeman-giti** [comment]
I will do that today.

**Comment by twakeman-giti** [comment]
@chrispassas I checked and now it reverses my ips on a little endian file

**Comment by twakeman-giti** [comment]
@chrispassas I think I might see what is going on? So it looks like where you are calling `intToIP` the buffer that you are putting in there is being created by `binary.BigEndian` so it filps and then flips again? I am not sure

**Comment by chrispassas** [comment]
@twakeman-giti
For example when I ran the test on **testdata/FT_RWGENERIC-v5-c0-L.dat**
The src/dst IP's output in reverse
Example test output
```bash
go test .
file_test.go:289: Test SrcIP:192.168.40.20 not equal to data row:20.40.168.192 file:testdata/FT_RWGENERIC-v5-c0-L.dat
```

You can see the Test was looking for **192.168.40.20** but the code read it in reverse **20.40.168.192**.

The other record sizes (56,68,88) all used the same code to read IP regardless of big/little endian.

I added the intToIP to reverse the IP for 52 record size and then my test passed.

I'm not sure what the issue is. Maybe my local silk tools version has a bug when creating the 52 byte record size files?

If possible can you give me a silk file in the 52 record size format?

Or can you checkout the latest version of this code and run it on your own local file. then run rwcut on the file and just compare the src/dst IP's to see if the library is parsing them correctly.

**Comment by twakeman-giti** [comment]
I am seeing the same with my local files both after the changes I made and after the changes you made. I am working on creating a file that I can share with but cannot share the ones I have locally.  When I get one created I will just add it to testdata in my fork.

**Comment by twakeman-giti** [comment]
@chrispassas 
I uploaded one file to my fork for testing but your changes worked for that particular file. I need to investigate further into what is happening with the files that we have. I ran your changes against another random file in our dataset and the outputs were as expected. I think your changes work as intended and there is something funky with some of the files I have here in our dataset. Thank you for your help and responsiveness.

**Comment by chrispassas** [comment]
@twakeman-giti thank you for helping me validate if these changes are correct. It's odd to me all the formats work the same for reading IPs but this one is a special case. If you confirm the changes work correctly then we can finally move on.

**Comment by twakeman-giti** [comment]
I would say that your changes work as intended and I still have some testing to do on the datasets that I have.

**Pull request merged**
